// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArGaZveW7M3SiUfZBTMNkyRgGdcYA3my0',
    appId: '1:16655676240:web:388dc81e9fddcafb83b255',
    messagingSenderId: '16655676240',
    projectId: 'to-do-app-58c31',
    authDomain: 'to-do-app-58c31.firebaseapp.com',
    storageBucket: 'to-do-app-58c31.appspot.com',
    measurementId: 'G-BYQ4S0NS85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi8rKxHj_yWYxDxwjXks4RC82VWoAkx7k',
    appId: '1:16655676240:android:59e6d4d0087eb16f83b255',
    messagingSenderId: '16655676240',
    projectId: 'to-do-app-58c31',
    storageBucket: 'to-do-app-58c31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlzdwvW48r-WWDi7CBTY7xBYbj7trRmQ',
    appId: '1:16655676240:ios:d9a0b2436939188383b255',
    messagingSenderId: '16655676240',
    projectId: 'to-do-app-58c31',
    storageBucket: 'to-do-app-58c31.appspot.com',
    iosClientId: '16655676240-8pepcbibk9vqrdva3ril62so331jms47.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlzdwvW48r-WWDi7CBTY7xBYbj7trRmQ',
    appId: '1:16655676240:ios:d9a0b2436939188383b255',
    messagingSenderId: '16655676240',
    projectId: 'to-do-app-58c31',
    storageBucket: 'to-do-app-58c31.appspot.com',
    iosClientId: '16655676240-8pepcbibk9vqrdva3ril62so331jms47.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
